name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile.dev

      # - name: Run s3-sync-action
      #   uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read --follow-symlinks --delete
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_S3_BUCKET: "elasticbeanstalk-ap-northeast-2-828981026636"
      #     AWS_REGION: "ap-northeast-2"

      - name: Elastic Beanstalk Deployment
        uses: kumarshivam12/Aws-ElasticBeanstalk@v1.4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          EB-BUCKET-NAME: "elasticbeanstalk-ap-northeast-2-828981026636"
          APPLICATION-NAME: docker-react-app-test
          EB-ENV-NAME: Dockerreactapptest-env
          AWS-REGION: "ap-northeast-2"

      # - name: Beanstalk Deploy
      #   uses: einaregilsson/beanstalk-deploy@v21
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     application_name: docker-react-app-test
      #     environment_name: Dockerreactapptest-env
      #     region: "ap-northeast-2"
      #     version_label: github-action-${{steps.current-time.outputs.formattedTime}}
